# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "MuhammadWara/waraspring"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "MuhammadWara-Personal-GitToken"
    stage: "clone"
    commands:
      - "ls -la"
      - "pwd"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "muhammadwara/waraspring"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test "
    type: "freestyle" # Run any command
    image: "gradle:6.8
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "echo 'Muhammad Wara First Codefresh Pipeline'"
      - "gradle build"
      - "gradle test"
    stage: "building"
