name: deploy

on:
   workflow_run:
    workflows: [gradle]
    types:
    - completed  
 
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      run: |
        echo The running PID from the main action is: " +  process.env.VERSION"
        echo "This is version"
        echo ${{ env.VERSION }}
    - name: 'Download artifact'
      uses: actions/github-script@v5
      with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

    - name: 'Unzip artifact'
      run: |
         unzip visuval.zip
         ls -lah
         cat visuval.txt

