name: deploy

on:
   workflow_run:
    workflows: [gradle]
    types:
    - completed  
 
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      run: |
        echo The running PID from the main action is: " +  process.env.VERSION"
        echo "This is version"
        echo ${{ env.VERSION }}
 
