name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
      env:
        ARTIFACTORY_USERNAME: ${{secrets.ARTIFACTORY_USERNAME}}
        ARTIFACTORY_PASSWORD: ${{secrets.ARTIFACTORY_PASSWORD}}        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean with Gradle
      run: ./gradlew clean      
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact 
      run: ./gradlew uploadArchives
