name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    env:
      ARTIFACTORY_USERNAME: Khanwara1@gmail.com
      #ARTIFACTORY_PASSWORD: ${{ secrets.MySec.ARTIFACTORY_PASSWORD}}
      #ARTIFACTORY_PASSSSWORD: ${{env.API_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
 
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        printenv
        export ARTIFACTORY_PASSWORD=${{ secrets.MySec.ARTIFACTORY_PASSWORD}}
    - name: Clean with Gradle
      run: ./gradlew clean      
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact 
      run: ./gradlew uploadArchives
